// test_course_parity.mjs — the JS pace model must equal the Python one.
//
// `course-plan.js` deliberately reimplements `course_lens.pace_table()` so the
// browser can price any target without a sync (design D5). Both the README and
// the module header claim the two are "pinned to each other" — this file is
// what makes that true, rather than an assertion nobody checks.
//
// The oracle is fixtures/course/sonthofen-pace-tables.json, generated by the
// PYTHON engine over the real course. Two tests hold the loop closed:
//   • this file asserts the JS output equals the fixture, and
//   • test_course_lens.py asserts the PYTHON output still equals it too,
// so drift on either side fails a test instead of silently splitting the two.
import assert from "node:assert";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { paceTable, basePaceSecPerKm, cautionCostSeconds } from "./course-plan.js";

const ROOT = dirname(fileURLToPath(import.meta.url));
const LENS = JSON.parse(await readFile(join(ROOT, "fixtures/course/sonthofen-lens.json"), "utf8"));
const ORACLE = JSON.parse(await readFile(join(ROOT, "fixtures/course/sonthofen-pace-tables.json"), "utf8"));

const FIELDS = ["km", "startM", "endM", "partial", "grade", "lengthM",
                "paceSecPerKm", "secondsForKm", "cumulativeSeconds"];

let checked = 0;
for (const c of ORACLE.cases) {
  const got = paceTable(LENS, c.target, c.decline);
  const label = `target=${c.target} decline=${c.decline}`;
  assert.strictEqual(got.length, c.rows.length, `${label}: row count`);
  for (let i = 0; i < got.length; i++) {
    for (const f of FIELDS) {
      assert.deepStrictEqual(got[i][f], c.rows[i][f],
        `${label}: row ${i} (km ${c.rows[i].km}) field '${f}' — ` +
        `js ${JSON.stringify(got[i][f])} vs python ${JSON.stringify(c.rows[i][f])}`);
    }
    checked++;
  }
}
assert.ok(checked > 100, "the oracle must actually cover something");

// The oracle covers the shapes that historically diverged:
// a partial final row, a decline threshold of exactly 0, and a non-preset target.
const partialCase = ORACLE.cases[0].rows.at(-1);
assert.strictEqual(partialCase.partial, true, "the oracle includes the partial stub row");
assert.ok(partialCase.endM > partialCase.startM);
assert.ok(partialCase.km * 1000 > partialCase.endM,
  "…and that stub is exactly the row whose label overshoots the finish");
assert.ok(ORACLE.cases.some((c) => c.decline === 0), "the oracle covers decline=0");
assert.ok(ORACLE.cases.some((c) => c.decline == null), "…and model-optimal");

// ── derived helpers ─────────────────────────────────────────────────────────
// The base pace is the quantity the table is built from, not any one row's
// pace: rebuilding a table from it must reproduce the target exactly.
const SRC = LENS.perKm.filter((r) => r && r.factor);
for (const target of [7199, 7308, 8068]) {
  const base = basePaceSecPerKm(LENS, target);
  const rows = paceTable(LENS, target);
  // The defining property: every row's pace is the base scaled by that row's
  // stored cost factor. If base were a near-flat kilometre's pace (the bug this
  // guards) the ratios would all be off by that kilometre's residual grade.
  for (let i = 0; i < rows.length; i++) {
    assert.ok(Math.abs(rows[i].paceSecPerKm / base - SRC[i].factor) < 0.002,
      `target ${target} row ${i}: pace/base ${rows[i].paceSecPerKm / base} != factor ${SRC[i].factor}`);
  }
  // …and the whole table still spends exactly the target
  const spent = rows.reduce((a, r) => a + r.secondsForKm, 0);
  assert.ok(Math.abs(spent - target) < 1, `target ${target}: table spends ${spent}`);
  // A course that costs time means the flat-equivalent base is FASTER than the
  // plain distance-average pace — the quantity the helper must not return.
  const avg = target / (LENS.distanceM / 1000);
  assert.ok(base < avg, `base ${base} must beat distance-average ${avg}`);
}
assert.strictEqual(basePaceSecPerKm(LENS, 0), null);
assert.strictEqual(basePaceSecPerKm(null, 7199), null);

// Caution cost must track the threshold it is given, and agree with the two
// course-level fractions Python stored at their own thresholds.
const steep = cautionCostSeconds(LENS, 7199, -0.02);
const every = cautionCostSeconds(LENS, 7199, 0);
assert.ok(Math.abs(steep - LENS.steepDescentGiveawayFraction * 7199) < 0.5,
  "steep-threshold cost matches the stored steep fraction");
assert.ok(Math.abs(every - LENS.descentGiveawayFraction * 7199) < 0.5,
  "zero-threshold cost matches the stored all-descents fraction");
assert.ok(every > steep, "declining more descent must cost more");
assert.ok(cautionCostSeconds(LENS, 7199, -0.5) < 0.5,
  "a threshold no descent reaches costs nothing");
assert.strictEqual(cautionCostSeconds(LENS, 0), null);

console.log(`ALL PASS (${checked} rows compared across ${ORACLE.cases.length} cases)`);
